{% set name = "brunsli" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/google/brunsli/
  git_rev: v{{ version }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
  - {{ pin_subpackage('brunsli') }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - brotli
    - gtest

test:
  commands:
    - test -f ${PREFIX}/lib/libbrunslidec-c${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libbrunslienc-c${SHLIB_EXT}  # [not win]

about:
  home: https://github.com/google/brunsli
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Practical JPEG Repacker'
  description: |
    Brunsli is a lossless JPEG repacking library.
    Brunsli allows for a 22% decrease in file size while allowing the original JPEG to be recovered byte-by-byte.
